# This file is only used to build multiple images
version: '3'

services:
  php7.4:
    image: ${COMPOSE_BUILD_NAME}:7.4
    build:
      dockerfile: 7.4/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - COMPOSER_VERSION=2.0.9
        - PHP_VERSION=7.4
        - VCS_REF=$VCS_REF
  php7.3:
    image: ${COMPOSE_BUILD_NAME}:7.3
    build:
      dockerfile: 7.3/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - COMPOSER_VERSION=2.0.9
        - PHP_VERSION=7.3
        - VCS_REF=$VCS_REF
  php7.2:
    image: ${COMPOSE_BUILD_NAME}:7.2
    build:
      dockerfile: 7.2/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - COMPOSER_VERSION=2.0.9
        - PHP_VERSION=7.2
        - VCS_REF=$VCS_REF
  php7.1:
    image: ${COMPOSE_BUILD_NAME}:7.1
    build:
      dockerfile: 7.1/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - COMPOSER_VERSION=2.0.9
        - PHP_VERSION=7.1
        - VCS_REF=$VCS_REF
