name: hadolint
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - 7.4
          - 7.3
          - 7.2
          - 7.1
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: make "php$PHP_VERSION"
