name: hadolint
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - 7.4
          - 7.3
          - 7.2
          - 7.1
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: make "php$PHP_VERSION"
      - name: Fix folder permissions
        run: chmod --recursive a+wrx .
      - name: Test container
        run: >
          docker run
          -it
          --volume $(pwd):/var/www/app:rw
          --user dev
          "php-container:$PHP_VERSION"
          bash ./test.sh
